#
# Copyright © 2025 BellSoft (info@bell-sw.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

FROM bellsoft/liberica-runtime-container:jdk-21-stream-musl as builder

ARG project
ENV project=${project}

WORKDIR /app
COPY .mvn/ .mvn/
COPY mvnw ./
COPY pom.xml ./
COPY chat-api ./chat-api
COPY bot-assistant ./bot-assistant
RUN ./mvnw clean package -pl ${project} -am -Dmaven.test.skip=true


FROM bellsoft/liberica-runtime-container:jre-21-cds-musl as optimizer

WORKDIR /app
COPY --from=builder /app/${project}/target/${project}-1.0-SNAPSHOT.jar ${project}.jar
RUN java -Djarmode=tools -jar ${project}.jar extract --layers --launcher


FROM bellsoft/liberica-runtime-container:jre-21-cds-musl

RUN apk add curl
WORKDIR /app
ENTRYPOINT ["java", "-Dspring.aot.enabled=true", "-XX:SharedArchiveFile=application.jsa", "org.springframework.boot.loader.launch.JarLauncher"]
COPY --from=optimizer /app/${project}/dependencies/ ./
COPY --from=optimizer /app/${project}/spring-boot-loader/ ./
COPY --from=optimizer /app/${project}/snapshot-dependencies/ ./
COPY --from=optimizer /app/${project}/application/ ./
RUN java -Dspring.aot.enabled=true -XX:ArchiveClassesAtExit=./application.jsa -Dspring.context.exit=onRefresh org.springframework.boot.loader.launch.JarLauncher