#
# Copyright © 2025 BellSoft (info@bell-sw.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

FROM bellsoft/liberica-native-image-kit-container:jdk-21-nik-23.1.6-stream-musl as builder

RUN apk add libstdc++
WORKDIR /app
ADD chat-api /app/chat-api
ADD pom.xml ./
RUN cd chat-api && ./mvnw -Dmaven.test.skip=true -Pnative native:compile


FROM bellsoft/alpaquita-linux-base:stream-musl

RUN apk add curl
WORKDIR /app
EXPOSE 8080
ENTRYPOINT ["/app/chat"]
COPY --from=builder /app/chat-api/target/native/chat /app/chat